# Imports

In [12]:
import pandas as pd
from datetime import date, timedelta, datetime

In [5]:
my_date = date(2025, 3, 15)

In [6]:
print(my_date.strftime("%B %d, %Y"))
print(f'{my_date.year} is the year')
print(f'{my_date.month} is the month')
print(f'{my_date.day} is the day')

March 15, 2025
2025 is the year
3 is the month
15 is the day

In [7]:
meeting_time = datetime(2025, 10, 8, 16, 45, 30)

print(f'{meeting_time.year} is the year')
print(f'{meeting_time.month} is the month')
print(f'{meeting_time.day} is the day')
print(f'{meeting_time.hour} is the hour')
print(f'{meeting_time.minute} is the minute')
print(f'{meeting_time.second} is the second')

2025 is the year
10 is the month
8 is the day
16 is the hour
45 is the minute
30 is the second

# To String and visa versa

In [8]:
meeting_time.strftime("%B %d, %Y at %I:%M:%S %p")
meeting_time.strftime("%Y-%m-%d")
meeting_time.strftime("%Y-%m-%d")

'2025-10-08'

In [18]:
from time import strptime


dtime = strptime("2025-12-31", "%Y-%m-%d")
print(f'{dtime.tm_year}-{dtime.tm_mon}-{dtime.tm_mday} ')

2025-12-31

# Timedelta & Date Arithmetic

In [19]:
start = date(2025, 1, 10)
end = date(2025, 2, 5)
duration = (end - start).days
print(f'The duration is {duration} days')

The duration is 26 days

In [27]:
days_after_start = start + timedelta(days=10)
days_before_start = start - timedelta(days=14)
weeks_after_start = start + timedelta(weeks=3)
the_day = datetime(2025, 2, 18, 11, 23, 10) + timedelta(hours=5, minutes=20, seconds=45)
the_day.strftime("%B %d, %Y at %I:%M:%S %p")

'February 18, 2025 at 04:43:55 PM'

# Date in Pandas

In [ ]:
df_dates = pd.DataFrame({
    "customer_id": [101, 102, 103, 104, 105],
    "signup_date": ["2024-01-15", "2024-02-20", "2024-03-05", "2024-03-18", "2024-04-10"],
    "last_purchase": ["2024-06-01", "2024-06-15", "2024-07-01", "2024-07-08", "2024-07-12"]
})

df_dates

   customer_id signup_date last_purchase
0          101  2024-01-15    2024-06-01
1          102  2024-02-20    2024-06-15
2          103  2024-03-05    2024-07-01
3          104  2024-03-18    2024-07-08
4          105  2024-04-10    2024-07-12

In [29]:
df_dates.dtypes

customer_id      int64
signup_date        str
last_purchase      str
dtype: object

In [30]:
df_dates["signup_date"] = pd.to_datetime(df_dates["signup_date"])
df_dates["last_purchase"] = pd.to_datetime(df_dates["last_purchase"])
df_dates.dtypes

customer_id               int64
signup_date      datetime64[us]
last_purchase    datetime64[us]
dtype: object

In [34]:
df_dates["signup_year"] = df_dates["signup_date"].dt.year
df_dates["signup_month"] = df_dates["signup_date"].dt.month
df_dates["signup_day"] = df_dates["signup_date"].dt.day
df_dates["last_purchase_year"] = df_dates["last_purchase"].dt.year
df_dates["last_purchase_month"] = df_dates["last_purchase"].dt.month
df_dates["last_purchase_day"] = df_dates["last_purchase"].dt.day
df_dates

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day,last_purchase_year,last_purchase_month,last_purchase_day
0,101,2024-01-15,2024-06-01,2024,1,15,2024,6,1
1,102,2024-02-20,2024-06-15,2024,2,20,2024,6,15
2,103,2024-03-05,2024-07-01,2024,3,5,2024,7,1
3,104,2024-03-18,2024-07-08,2024,3,18,2024,7,8
4,105,2024-04-10,2024-07-12,2024,4,10,2024,7,12

## Day of the week & weekend flag

In [35]:
df_dates['signup_dow'] = df_dates['signup_date'].dt.dayofweek
df_dates['is_weekend'] = df_dates['signup_dow'].isin([5, 6])    
df_dates

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day,last_purchase_year,last_purchase_month,last_purchase_day,signup_dow,is_weekend
0,101,2024-01-15,2024-06-01,2024,1,15,2024,6,1,0,False
1,102,2024-02-20,2024-06-15,2024,2,20,2024,6,15,1,False
2,103,2024-03-05,2024-07-01,2024,3,5,2024,7,1,1,False
3,104,2024-03-18,2024-07-08,2024,3,18,2024,7,8,0,False
4,105,2024-04-10,2024-07-12,2024,4,10,2024,7,12,2,False

## `days_between_signup_and_purchase`

In [36]:
df_dates['days_between_signup_and_purchase'] = (df_dates['last_purchase'] - df_dates['signup_date']).dt.days
df_dates

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day,last_purchase_year,last_purchase_month,last_purchase_day,signup_dow,is_weekend,days_between_signup_and_purchase
0,101,2024-01-15,2024-06-01,2024,1,15,2024,6,1,0,False,138
1,102,2024-02-20,2024-06-15,2024,2,20,2024,6,15,1,False,116
2,103,2024-03-05,2024-07-01,2024,3,5,2024,7,1,1,False,118
3,104,2024-03-18,2024-07-08,2024,3,18,2024,7,8,0,False,112
4,105,2024-04-10,2024-07-12,2024,4,10,2024,7,12,2,False,93

## Filter Data

In [37]:
df_dates[df_dates['signup_date'] > "2024-03-01"]

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day,last_purchase_year,last_purchase_month,last_purchase_day,signup_dow,is_weekend,days_between_signup_and_purchase
2,103,2024-03-05,2024-07-01,2024,3,5,2024,7,1,1,False,118
3,104,2024-03-18,2024-07-08,2024,3,18,2024,7,8,0,False,112
4,105,2024-04-10,2024-07-12,2024,4,10,2024,7,12,2,False,93

In [56]:
df_dates[df_dates['signup_date'].dt.month == 3]
df_dates[df_dates['signup_date'].dt.year == 2024]

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day,last_purchase_year,last_purchase_month,last_purchase_day,signup_dow,is_weekend,days_between_signup_and_purchase
0,101,2024-01-15,2024-06-01,2024,1,15,2024,6,1,0,False,138
1,102,2024-02-20,2024-06-15,2024,2,20,2024,6,15,1,False,116
2,103,2024-03-05,2024-07-01,2024,3,5,2024,7,1,1,False,118
3,104,2024-03-18,2024-07-08,2024,3,18,2024,7,8,0,False,112
4,105,2024-04-10,2024-07-12,2024,4,10,2024,7,12,2,False,93

## Sort by signup date

In [57]:
df_dates.sort_values(by='signup_date')

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day,last_purchase_year,last_purchase_month,last_purchase_day,signup_dow,is_weekend,days_between_signup_and_purchase
0,101,2024-01-15,2024-06-01,2024,1,15,2024,6,1,0,False,138
1,102,2024-02-20,2024-06-15,2024,2,20,2024,6,15,1,False,116
2,103,2024-03-05,2024-07-01,2024,3,5,2024,7,1,1,False,118
3,104,2024-03-18,2024-07-08,2024,3,18,2024,7,8,0,False,112
4,105,2024-04-10,2024-07-12,2024,4,10,2024,7,12,2,False,93

## Date ranges

In [66]:
start_date = pd.to_datetime("2024-07-01")
end_date = start_date + timedelta(days=120)
pd.date_range(start=start_date, end=end_date, freq='10D')
pd.date_range(start=start_date, freq='D', periods=10)

DatetimeIndex(['2024-07-01', '2024-07-02', '2024-07-03', '2024-07-04',
               '2024-07-05', '2024-07-06', '2024-07-07', '2024-07-08',
               '2024-07-09', '2024-07-10'],
              dtype='datetime64[us]', freq='D')

In [68]:
start_date = pd.to_datetime("2024-01-01")
pd.date_range(start=start_date, freq='MS', periods=12)

DatetimeIndex(['2024-01-01', '2024-02-01', '2024-03-01', '2024-04-01',
               '2024-05-01', '2024-06-01', '2024-07-01', '2024-08-01',
               '2024-09-01', '2024-10-01', '2024-11-01', '2024-12-01'],
              dtype='datetime64[us]', freq='MS')

## Data Frame with date range
### Derived columns:
1. year
2. month
3. day
4. day_name
5. dow
6. is_weekend

In [ ]:
df_new_dates=pd.DataFrame({
    'date': pd.date_range(start=start_date, freq='D', periods=15),
    'sales': [100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650, 700, 750, 800]
    })
df_new_dates

         date  sales
0  2024-01-01    100
1  2024-01-02    150
2  2024-01-03    200
3  2024-01-04    250
4  2024-01-05    300
5  2024-01-06    350
6  2024-01-07    400
7  2024-01-08    450
8  2024-01-09    500
9  2024-01-10    550
10 2024-01-11    600
11 2024-01-12    650
12 2024-01-13    700
13 2024-01-14    750
14 2024-01-15    800

In [72]:
df_new_dates['year'] = df_new_dates['date'].dt.year
df_new_dates['month'] = df_new_dates['date'].dt.month
df_new_dates['day'] = df_new_dates['date'].dt.day
df_new_dates['dow'] = df_new_dates['date'].dt.day_of_week
df_new_dates['day_name'] = df_new_dates['date'].dt.day_name()
df_new_dates['is_weekend'] = df_new_dates['day_name'].isin(['Saturday', 'Sunday'])
df_new_dates

         date  sales  year  month  day  dow   day_name  is_weekend
0  2024-01-01    100  2024      1    1    0     Monday       False
1  2024-01-02    150  2024      1    2    1    Tuesday       False
2  2024-01-03    200  2024      1    3    2  Wednesday       False
3  2024-01-04    250  2024      1    4    3   Thursday       False
4  2024-01-05    300  2024      1    5    4     Friday       False
5  2024-01-06    350  2024      1    6    5   Saturday        True
6  2024-01-07    400  2024      1    7    6     Sunday        True
7  2024-01-08    450  2024      1    8    0     Monday       False
8  2024-01-09    500  2024      1    9    1    Tuesday       False
9  2024-01-10    550  2024      1   10    2  Wednesday       False
10 2024-01-11    600  2024      1   11    3   Thursday       False
11 2024-01-12    650  2024      1   12    4     Friday       False
12 2024-01-13    700  2024      1   13    5   Saturday        True
13 2024-01-14    750  2024      1   14    6     Sunday        True
14 2024-01-15    800  2024      1   15    0     Monday       False

## Beginning and End of Month for One Date

In [75]:
some_date = pd.Timestamp("2024-08-18")
print(f'{some_date.year} is the year')
print(f'{some_date.month} is the month')
print(f'{some_date.day} is the day')
print(f'{some_date.hour} is the hour')
print(f'{some_date.minute} is the minute')
print(f'{some_date.second} is the second')
print(f'{some_date.date()} is the date')

2024 is the year
8 is the month
18 is the day
0 is the hour
0 is the minute
0 is the second
2024-08-18 is the date

In [80]:
print(f'{some_date.to_period("M").start_time.date()} is the month\'s start')
print(f'{some_date.to_period("M").end_time.date()} is the month\'s end')

2024-08-01 is the month's start
2024-08-31 is the month's end

In [88]:
df_dates["month_start"] = df_dates["signup_date"].dt.to_period("M").dt.start_time
df_dates["month_end"] = df_dates["signup_date"].dt.to_period("M").dt.end_time
# print(df_dates["signup_date"].dt.to_period("M").dt.start_time)
df_dates

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day,last_purchase_year,last_purchase_month,last_purchase_day,signup_dow,is_weekend,days_between_signup_and_purchase,month_start,month_end
0,101,2024-01-15,2024-06-01,2024,1,15,2024,6,1,0,False,138,2024-01-01,2024-01-31 23:59:59.999999
1,102,2024-02-20,2024-06-15,2024,2,20,2024,6,15,1,False,116,2024-02-01,2024-02-29 23:59:59.999999
2,103,2024-03-05,2024-07-01,2024,3,5,2024,7,1,1,False,118,2024-03-01,2024-03-31 23:59:59.999999
3,104,2024-03-18,2024-07-08,2024,3,18,2024,7,8,0,False,112,2024-03-01,2024-03-31 23:59:59.999999
4,105,2024-04-10,2024-07-12,2024,4,10,2024,7,12,2,False,93,2024-04-01,2024-04-30 23:59:59.999999